use std::error::Error;

pub fn quit(args: Vec<&str>) -> Result<(), Box<dyn Error>> {
	todo!()
}
